spring.application.name=backend

# Database Configuration with Environment Variables Fallbacks to H2
spring.datasource.url=${DB_URI:jdbc:h2:mem:testdb}
spring.datasource.driverClassName=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true